//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: sum.proto
//
package com.feivirus.hbase.coprocessor.autogenerated;
//
public final class Sum {
//  private Sum() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  public interface SumRequestOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:SumRequest)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>required string family = 1;</code>
//     * @return Whether the family field is set.
//     */
//    boolean hasFamily();
//    /**
//     * <code>required string family = 1;</code>
//     * @return The family.
//     */
//    String getFamily();
//    /**
//     * <code>required string family = 1;</code>
//     * @return The bytes for family.
//     */
//    com.google.protobuf.ByteString
//        getFamilyBytes();
//
//    /**
//     * <code>required string column = 2;</code>
//     * @return Whether the column field is set.
//     */
//    boolean hasColumn();
//    /**
//     * <code>required string column = 2;</code>
//     * @return The column.
//     */
//    String getColumn();
//    /**
//     * <code>required string column = 2;</code>
//     * @return The bytes for column.
//     */
//    com.google.protobuf.ByteString
//        getColumnBytes();
//  }
//  /**
//   * Protobuf type {@code SumRequest}
//   */
//  public  static final class SumRequest extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:SumRequest)
//      SumRequestOrBuilder {
//  private static final long serialVersionUID = 0L;
//    // Use SumRequest.newBuilder() to construct.
//    private SumRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private SumRequest() {
//      family_ = "";
//      column_ = "";
//    }
//
//    @Override
//    @SuppressWarnings({"unused"})
//    protected Object newInstance(
//        UnusedPrivateParameter unused) {
//      return new SumRequest();
//    }
//
//    @Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return this.unknownFields;
//    }
//    private SumRequest(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      if (extensionRegistry == null) {
//        throw new NullPointerException();
//      }
//      int mutable_bitField0_ = 0;
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            case 10: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000001;
//              family_ = bs;
//              break;
//            }
//            case 18: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000002;
//              column_ = bs;
//              break;
//            }
//            default: {
//              if (!parseUnknownField(
//                  input, unknownFields, extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return Sum.internal_static_SumRequest_descriptor;
//    }
//
//    @Override
//    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return Sum.internal_static_SumRequest_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              SumRequest.class, Builder.class);
//    }
//
//    private int bitField0_;
//    public static final int FAMILY_FIELD_NUMBER = 1;
//    private volatile Object family_;
//    /**
//     * <code>required string family = 1;</code>
//     * @return Whether the family field is set.
//     */
//    public boolean hasFamily() {
//      return ((bitField0_ & 0x00000001) != 0);
//    }
//    /**
//     * <code>required string family = 1;</code>
//     * @return The family.
//     */
//    public String getFamily() {
//      Object ref = family_;
//      if (ref instanceof String) {
//        return (String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          family_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>required string family = 1;</code>
//     * @return The bytes for family.
//     */
//    public com.google.protobuf.ByteString
//        getFamilyBytes() {
//      Object ref = family_;
//      if (ref instanceof String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (String) ref);
//        family_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int COLUMN_FIELD_NUMBER = 2;
//    private volatile Object column_;
//    /**
//     * <code>required string column = 2;</code>
//     * @return Whether the column field is set.
//     */
//    public boolean hasColumn() {
//      return ((bitField0_ & 0x00000002) != 0);
//    }
//    /**
//     * <code>required string column = 2;</code>
//     * @return The column.
//     */
//    public String getColumn() {
//      Object ref = column_;
//      if (ref instanceof String) {
//        return (String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          column_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>required string column = 2;</code>
//     * @return The bytes for column.
//     */
//    public com.google.protobuf.ByteString
//        getColumnBytes() {
//      Object ref = column_;
//      if (ref instanceof String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (String) ref);
//        column_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    private byte memoizedIsInitialized = -1;
//    @Override
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      if (!hasFamily()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      if (!hasColumn()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    @Override
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (((bitField0_ & 0x00000001) != 0)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, family_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, column_);
//      }
//      unknownFields.writeTo(output);
//    }
//
//    @Override
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (((bitField0_ & 0x00000001) != 0)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, family_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, column_);
//      }
//      size += unknownFields.getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @Override
//    public boolean equals(final Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof SumRequest)) {
//        return super.equals(obj);
//      }
//      SumRequest other = (SumRequest) obj;
//
//      if (hasFamily() != other.hasFamily()) return false;
//      if (hasFamily()) {
//        if (!getFamily()
//            .equals(other.getFamily())) return false;
//      }
//      if (hasColumn() != other.hasColumn()) return false;
//      if (hasColumn()) {
//        if (!getColumn()
//            .equals(other.getColumn())) return false;
//      }
//      if (!unknownFields.equals(other.unknownFields)) return false;
//      return true;
//    }
//
//    @Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      if (hasFamily()) {
//        hash = (37 * hash) + FAMILY_FIELD_NUMBER;
//        hash = (53 * hash) + getFamily().hashCode();
//      }
//      if (hasColumn()) {
//        hash = (37 * hash) + COLUMN_FIELD_NUMBER;
//        hash = (53 * hash) + getColumn().hashCode();
//      }
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static SumRequest parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static SumRequest parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static SumRequest parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static SumRequest parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static SumRequest parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static SumRequest parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static SumRequest parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static SumRequest parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static SumRequest parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static SumRequest parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static SumRequest parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static SumRequest parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    @Override
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(SumRequest prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    @Override
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code SumRequest}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:SumRequest)
//        SumRequestOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return Sum.internal_static_SumRequest_descriptor;
//      }
//
//      @Override
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return Sum.internal_static_SumRequest_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                SumRequest.class, Builder.class);
//      }
//
//      // Construct using com.feivirus.autogenerated.Sum.SumRequest.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      @Override
//      public Builder clear() {
//        super.clear();
//        family_ = "";
//        bitField0_ = (bitField0_ & ~0x00000001);
//        column_ = "";
//        bitField0_ = (bitField0_ & ~0x00000002);
//        return this;
//      }
//
//      @Override
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return Sum.internal_static_SumRequest_descriptor;
//      }
//
//      @Override
//      public SumRequest getDefaultInstanceForType() {
//        return SumRequest.getDefaultInstance();
//      }
//
//      @Override
//      public SumRequest build() {
//        SumRequest result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      @Override
//      public SumRequest buildPartial() {
//        SumRequest result = new SumRequest(this);
//        int from_bitField0_ = bitField0_;
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000001) != 0)) {
//          to_bitField0_ |= 0x00000001;
//        }
//        result.family_ = family_;
//        if (((from_bitField0_ & 0x00000002) != 0)) {
//          to_bitField0_ |= 0x00000002;
//        }
//        result.column_ = column_;
//        result.bitField0_ = to_bitField0_;
//        onBuilt();
//        return result;
//      }
//
//      @Override
//      public Builder clone() {
//        return super.clone();
//      }
//      @Override
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return super.setField(field, value);
//      }
//      @Override
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return super.clearField(field);
//      }
//      @Override
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return super.clearOneof(oneof);
//      }
//      @Override
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, Object value) {
//        return super.setRepeatedField(field, index, value);
//      }
//      @Override
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return super.addRepeatedField(field, value);
//      }
//      @Override
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof SumRequest) {
//          return mergeFrom((SumRequest)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(SumRequest other) {
//        if (other == SumRequest.getDefaultInstance()) return this;
//        if (other.hasFamily()) {
//          bitField0_ |= 0x00000001;
//          family_ = other.family_;
//          onChanged();
//        }
//        if (other.hasColumn()) {
//          bitField0_ |= 0x00000002;
//          column_ = other.column_;
//          onChanged();
//        }
//        this.mergeUnknownFields(other.unknownFields);
//        onChanged();
//        return this;
//      }
//
//      @Override
//      public final boolean isInitialized() {
//        if (!hasFamily()) {
//          return false;
//        }
//        if (!hasColumn()) {
//          return false;
//        }
//        return true;
//      }
//
//      @Override
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        SumRequest parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (SumRequest) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//      private int bitField0_;
//
//      private Object family_ = "";
//      /**
//       * <code>required string family = 1;</code>
//       * @return Whether the family field is set.
//       */
//      public boolean hasFamily() {
//        return ((bitField0_ & 0x00000001) != 0);
//      }
//      /**
//       * <code>required string family = 1;</code>
//       * @return The family.
//       */
//      public String getFamily() {
//        Object ref = family_;
//        if (!(ref instanceof String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            family_ = s;
//          }
//          return s;
//        } else {
//          return (String) ref;
//        }
//      }
//      /**
//       * <code>required string family = 1;</code>
//       * @return The bytes for family.
//       */
//      public com.google.protobuf.ByteString
//          getFamilyBytes() {
//        Object ref = family_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (String) ref);
//          family_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>required string family = 1;</code>
//       * @param value The family to set.
//       * @return This builder for chaining.
//       */
//      public Builder setFamily(
//          String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000001;
//        family_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string family = 1;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearFamily() {
//        bitField0_ = (bitField0_ & ~0x00000001);
//        family_ = getDefaultInstance().getFamily();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string family = 1;</code>
//       * @param value The bytes for family to set.
//       * @return This builder for chaining.
//       */
//      public Builder setFamilyBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000001;
//        family_ = value;
//        onChanged();
//        return this;
//      }
//
//      private Object column_ = "";
//      /**
//       * <code>required string column = 2;</code>
//       * @return Whether the column field is set.
//       */
//      public boolean hasColumn() {
//        return ((bitField0_ & 0x00000002) != 0);
//      }
//      /**
//       * <code>required string column = 2;</code>
//       * @return The column.
//       */
//      public String getColumn() {
//        Object ref = column_;
//        if (!(ref instanceof String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            column_ = s;
//          }
//          return s;
//        } else {
//          return (String) ref;
//        }
//      }
//      /**
//       * <code>required string column = 2;</code>
//       * @return The bytes for column.
//       */
//      public com.google.protobuf.ByteString
//          getColumnBytes() {
//        Object ref = column_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (String) ref);
//          column_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>required string column = 2;</code>
//       * @param value The column to set.
//       * @return This builder for chaining.
//       */
//      public Builder setColumn(
//          String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000002;
//        column_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string column = 2;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearColumn() {
//        bitField0_ = (bitField0_ & ~0x00000002);
//        column_ = getDefaultInstance().getColumn();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string column = 2;</code>
//       * @param value The bytes for column to set.
//       * @return This builder for chaining.
//       */
//      public Builder setColumnBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000002;
//        column_ = value;
//        onChanged();
//        return this;
//      }
//      @Override
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.setUnknownFields(unknownFields);
//      }
//
//      @Override
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:SumRequest)
//    }
//
//    // @@protoc_insertion_point(class_scope:SumRequest)
//    private static final SumRequest DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new SumRequest();
//    }
//
//    public static SumRequest getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    @Deprecated public static final com.google.protobuf.Parser<SumRequest>
//        PARSER = new com.google.protobuf.AbstractParser<SumRequest>() {
//      @Override
//      public SumRequest parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return new SumRequest(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<SumRequest> parser() {
//      return PARSER;
//    }
//
//    @Override
//    public com.google.protobuf.Parser<SumRequest> getParserForType() {
//      return PARSER;
//    }
//
//    @Override
//    public SumRequest getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  public interface SumResponseOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:SumResponse)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>required int64 sum = 1 [default = 0];</code>
//     * @return Whether the sum field is set.
//     */
//    boolean hasSum();
//    /**
//     * <code>required int64 sum = 1 [default = 0];</code>
//     * @return The sum.
//     */
//    long getSum();
//  }
//  /**
//   * Protobuf type {@code SumResponse}
//   */
//  public  static final class SumResponse extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:SumResponse)
//      SumResponseOrBuilder {
//  private static final long serialVersionUID = 0L;
//    // Use SumResponse.newBuilder() to construct.
//    private SumResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private SumResponse() {
//    }
//
//    @Override
//    @SuppressWarnings({"unused"})
//    protected Object newInstance(
//        UnusedPrivateParameter unused) {
//      return new SumResponse();
//    }
//
//    @Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return this.unknownFields;
//    }
//    private SumResponse(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      if (extensionRegistry == null) {
//        throw new NullPointerException();
//      }
//      int mutable_bitField0_ = 0;
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            case 8: {
//              bitField0_ |= 0x00000001;
//              sum_ = input.readInt64();
//              break;
//            }
//            default: {
//              if (!parseUnknownField(
//                  input, unknownFields, extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return Sum.internal_static_SumResponse_descriptor;
//    }
//
//    @Override
//    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return Sum.internal_static_SumResponse_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              SumResponse.class, Builder.class);
//    }
//
//    private int bitField0_;
//    public static final int SUM_FIELD_NUMBER = 1;
//    private long sum_;
//    /**
//     * <code>required int64 sum = 1 [default = 0];</code>
//     * @return Whether the sum field is set.
//     */
//    public boolean hasSum() {
//      return ((bitField0_ & 0x00000001) != 0);
//    }
//    /**
//     * <code>required int64 sum = 1 [default = 0];</code>
//     * @return The sum.
//     */
//    public long getSum() {
//      return sum_;
//    }
//
//    private byte memoizedIsInitialized = -1;
//    @Override
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      if (!hasSum()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    @Override
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (((bitField0_ & 0x00000001) != 0)) {
//        output.writeInt64(1, sum_);
//      }
//      unknownFields.writeTo(output);
//    }
//
//    @Override
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (((bitField0_ & 0x00000001) != 0)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt64Size(1, sum_);
//      }
//      size += unknownFields.getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @Override
//    public boolean equals(final Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof SumResponse)) {
//        return super.equals(obj);
//      }
//      SumResponse other = (SumResponse) obj;
//
//      if (hasSum() != other.hasSum()) return false;
//      if (hasSum()) {
//        if (getSum()
//            != other.getSum()) return false;
//      }
//      if (!unknownFields.equals(other.unknownFields)) return false;
//      return true;
//    }
//
//    @Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      if (hasSum()) {
//        hash = (37 * hash) + SUM_FIELD_NUMBER;
//        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
//            getSum());
//      }
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static SumResponse parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static SumResponse parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static SumResponse parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static SumResponse parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static SumResponse parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static SumResponse parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static SumResponse parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static SumResponse parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static SumResponse parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static SumResponse parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static SumResponse parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static SumResponse parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    @Override
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(SumResponse prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    @Override
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code SumResponse}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:SumResponse)
//        SumResponseOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return Sum.internal_static_SumResponse_descriptor;
//      }
//
//      @Override
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return Sum.internal_static_SumResponse_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                SumResponse.class, Builder.class);
//      }
//
//      // Construct using com.feivirus.autogenerated.Sum.SumResponse.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      @Override
//      public Builder clear() {
//        super.clear();
//        sum_ = 0L;
//        bitField0_ = (bitField0_ & ~0x00000001);
//        return this;
//      }
//
//      @Override
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return Sum.internal_static_SumResponse_descriptor;
//      }
//
//      @Override
//      public SumResponse getDefaultInstanceForType() {
//        return SumResponse.getDefaultInstance();
//      }
//
//      @Override
//      public SumResponse build() {
//        SumResponse result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      @Override
//      public SumResponse buildPartial() {
//        SumResponse result = new SumResponse(this);
//        int from_bitField0_ = bitField0_;
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000001) != 0)) {
//          result.sum_ = sum_;
//          to_bitField0_ |= 0x00000001;
//        }
//        result.bitField0_ = to_bitField0_;
//        onBuilt();
//        return result;
//      }
//
//      @Override
//      public Builder clone() {
//        return super.clone();
//      }
//      @Override
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return super.setField(field, value);
//      }
//      @Override
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return super.clearField(field);
//      }
//      @Override
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return super.clearOneof(oneof);
//      }
//      @Override
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, Object value) {
//        return super.setRepeatedField(field, index, value);
//      }
//      @Override
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return super.addRepeatedField(field, value);
//      }
//      @Override
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof SumResponse) {
//          return mergeFrom((SumResponse)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(SumResponse other) {
//        if (other == SumResponse.getDefaultInstance()) return this;
//        if (other.hasSum()) {
//          setSum(other.getSum());
//        }
//        this.mergeUnknownFields(other.unknownFields);
//        onChanged();
//        return this;
//      }
//
//      @Override
//      public final boolean isInitialized() {
//        if (!hasSum()) {
//          return false;
//        }
//        return true;
//      }
//
//      @Override
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        SumResponse parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (SumResponse) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//      private int bitField0_;
//
//      private long sum_ ;
//      /**
//       * <code>required int64 sum = 1 [default = 0];</code>
//       * @return Whether the sum field is set.
//       */
//      public boolean hasSum() {
//        return ((bitField0_ & 0x00000001) != 0);
//      }
//      /**
//       * <code>required int64 sum = 1 [default = 0];</code>
//       * @return The sum.
//       */
//      public long getSum() {
//        return sum_;
//      }
//      /**
//       * <code>required int64 sum = 1 [default = 0];</code>
//       * @param value The sum to set.
//       * @return This builder for chaining.
//       */
//      public Builder setSum(long value) {
//        bitField0_ |= 0x00000001;
//        sum_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required int64 sum = 1 [default = 0];</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearSum() {
//        bitField0_ = (bitField0_ & ~0x00000001);
//        sum_ = 0L;
//        onChanged();
//        return this;
//      }
//      @Override
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.setUnknownFields(unknownFields);
//      }
//
//      @Override
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:SumResponse)
//    }
//
//    // @@protoc_insertion_point(class_scope:SumResponse)
//    private static final SumResponse DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new SumResponse();
//    }
//
//    public static SumResponse getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    @Deprecated public static final com.google.protobuf.Parser<SumResponse>
//        PARSER = new com.google.protobuf.AbstractParser<SumResponse>() {
//      @Override
//      public SumResponse parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return new SumResponse(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<SumResponse> parser() {
//      return PARSER;
//    }
//
//    @Override
//    public com.google.protobuf.Parser<SumResponse> getParserForType() {
//      return PARSER;
//    }
//
//    @Override
//    public SumResponse getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  /**
//   * Protobuf service {@code SumService}
//   */
//  public static abstract class SumService
//      implements com.google.protobuf.Service {
//    protected SumService() {}
//
//    public interface Interface {
//      /**
//       * <code>rpc getSum(.SumRequest) returns (.SumResponse);</code>
//       */
//      public abstract void getSum(
//              com.google.protobuf.RpcController controller,
//              SumRequest request,
//              com.google.protobuf.RpcCallback<SumResponse> done);
//
//    }
//
//    public static com.google.protobuf.Service newReflectiveService(
//        final Interface impl) {
//      return new SumService() {
//        @Override
//        public  void getSum(
//            com.google.protobuf.RpcController controller,
//            SumRequest request,
//            com.google.protobuf.RpcCallback<SumResponse> done) {
//          impl.getSum(controller, request, done);
//        }
//
//      };
//    }
//
//    public static com.google.protobuf.BlockingService
//        newReflectiveBlockingService(final BlockingInterface impl) {
//      return new com.google.protobuf.BlockingService() {
//        public final com.google.protobuf.Descriptors.ServiceDescriptor
//            getDescriptorForType() {
//          return getDescriptor();
//        }
//
//        public final com.google.protobuf.Message callBlockingMethod(
//            com.google.protobuf.Descriptors.MethodDescriptor method,
//            com.google.protobuf.RpcController controller,
//            com.google.protobuf.Message request)
//            throws com.google.protobuf.ServiceException {
//          if (method.getService() != getDescriptor()) {
//            throw new IllegalArgumentException(
//              "Service.callBlockingMethod() given method descriptor for " +
//              "wrong service type.");
//          }
//          switch(method.getIndex()) {
//            case 0:
//              return impl.getSum(controller, (SumRequest)request);
//            default:
//              throw new AssertionError("Can't get here.");
//          }
//        }
//
//        public final com.google.protobuf.Message
//            getRequestPrototype(
//            com.google.protobuf.Descriptors.MethodDescriptor method) {
//          if (method.getService() != getDescriptor()) {
//            throw new IllegalArgumentException(
//              "Service.getRequestPrototype() given method " +
//              "descriptor for wrong service type.");
//          }
//          switch(method.getIndex()) {
//            case 0:
//              return SumRequest.getDefaultInstance();
//            default:
//              throw new AssertionError("Can't get here.");
//          }
//        }
//
//        public final com.google.protobuf.Message
//            getResponsePrototype(
//            com.google.protobuf.Descriptors.MethodDescriptor method) {
//          if (method.getService() != getDescriptor()) {
//            throw new IllegalArgumentException(
//              "Service.getResponsePrototype() given method " +
//              "descriptor for wrong service type.");
//          }
//          switch(method.getIndex()) {
//            case 0:
//              return SumResponse.getDefaultInstance();
//            default:
//              throw new AssertionError("Can't get here.");
//          }
//        }
//
//      };
//    }
//
//    /**
//     * <code>rpc getSum(.SumRequest) returns (.SumResponse);</code>
//     */
//    public abstract void getSum(
//        com.google.protobuf.RpcController controller,
//        SumRequest request,
//        com.google.protobuf.RpcCallback<SumResponse> done);
//
//    public static final
//        com.google.protobuf.Descriptors.ServiceDescriptor
//        getDescriptor() {
//      return Sum.getDescriptor().getServices().get(0);
//    }
//    public final com.google.protobuf.Descriptors.ServiceDescriptor
//        getDescriptorForType() {
//      return getDescriptor();
//    }
//
//    public final void callMethod(
//        com.google.protobuf.Descriptors.MethodDescriptor method,
//        com.google.protobuf.RpcController controller,
//        com.google.protobuf.Message request,
//        com.google.protobuf.RpcCallback<
//          com.google.protobuf.Message> done) {
//      if (method.getService() != getDescriptor()) {
//        throw new IllegalArgumentException(
//          "Service.callMethod() given method descriptor for wrong " +
//          "service type.");
//      }
//      switch(method.getIndex()) {
//        case 0:
//          this.getSum(controller, (SumRequest)request,
//            com.google.protobuf.RpcUtil.<SumResponse>specializeCallback(
//              done));
//          return;
//        default:
//          throw new AssertionError("Can't get here.");
//      }
//    }
//
//    public final com.google.protobuf.Message
//        getRequestPrototype(
//        com.google.protobuf.Descriptors.MethodDescriptor method) {
//      if (method.getService() != getDescriptor()) {
//        throw new IllegalArgumentException(
//          "Service.getRequestPrototype() given method " +
//          "descriptor for wrong service type.");
//      }
//      switch(method.getIndex()) {
//        case 0:
//          return SumRequest.getDefaultInstance();
//        default:
//          throw new AssertionError("Can't get here.");
//      }
//    }
//
//    public final com.google.protobuf.Message
//        getResponsePrototype(
//        com.google.protobuf.Descriptors.MethodDescriptor method) {
//      if (method.getService() != getDescriptor()) {
//        throw new IllegalArgumentException(
//          "Service.getResponsePrototype() given method " +
//          "descriptor for wrong service type.");
//      }
//      switch(method.getIndex()) {
//        case 0:
//          return SumResponse.getDefaultInstance();
//        default:
//          throw new AssertionError("Can't get here.");
//      }
//    }
//
//    public static Stub newStub(
//        com.google.protobuf.RpcChannel channel) {
//      return new Stub(channel);
//    }
//
//    public static final class Stub extends SumService implements Interface {
//      private Stub(com.google.protobuf.RpcChannel channel) {
//        this.channel = channel;
//      }
//
//      private final com.google.protobuf.RpcChannel channel;
//
//      public com.google.protobuf.RpcChannel getChannel() {
//        return channel;
//      }
//
//      public  void getSum(
//          com.google.protobuf.RpcController controller,
//          SumRequest request,
//          com.google.protobuf.RpcCallback<SumResponse> done) {
//        channel.callMethod(
//          getDescriptor().getMethods().get(0),
//          controller,
//          request,
//          SumResponse.getDefaultInstance(),
//          com.google.protobuf.RpcUtil.generalizeCallback(
//            done,
//            SumResponse.class,
//            SumResponse.getDefaultInstance()));
//      }
//    }
//
//    public static BlockingInterface newBlockingStub(
//        com.google.protobuf.BlockingRpcChannel channel) {
//      return new BlockingStub(channel);
//    }
//
//    public interface BlockingInterface {
//      public SumResponse getSum(
//              com.google.protobuf.RpcController controller,
//              SumRequest request)
//          throws com.google.protobuf.ServiceException;
//    }
//
//    private static final class BlockingStub implements BlockingInterface {
//      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
//        this.channel = channel;
//      }
//
//      private final com.google.protobuf.BlockingRpcChannel channel;
//
//      public SumResponse getSum(
//          com.google.protobuf.RpcController controller,
//          SumRequest request)
//          throws com.google.protobuf.ServiceException {
//        return (SumResponse) channel.callBlockingMethod(
//          getDescriptor().getMethods().get(0),
//          controller,
//          request,
//          SumResponse.getDefaultInstance());
//      }
//
//    }
//
//    // @@protoc_insertion_point(class_scope:SumService)
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_SumRequest_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_SumRequest_fieldAccessorTable;
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_SumResponse_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_SumResponse_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    String[] descriptorData = {
//      "\n\tsum.proto\",\n\nSumRequest\022\016\n\006family\030\001 \002(" +
//      "\t\022\016\n\006column\030\002 \002(\t\"\035\n\013SumResponse\022\016\n\003sum\030" +
//      "\001 \002(\003:\001021\n\nSumService\022#\n\006getSum\022\013.SumRe" +
//      "quest\032\014.SumResponseB)\n\032com.feivirus.auto" +
//      "generatedB\003SumH\001\210\001\001\240\001\001"
//    };
//    descriptor = com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        });
//    internal_static_SumRequest_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_SumRequest_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_SumRequest_descriptor,
//        new String[] { "Family", "Column", });
//    internal_static_SumResponse_descriptor =
//      getDescriptor().getMessageTypes().get(1);
//    internal_static_SumResponse_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_SumResponse_descriptor,
//        new String[] { "Sum", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
}
